// firebase_options.dart

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfOOhVnCloxCJZ5cqrl1-xBihbPVUK-sw',
    appId: '1:1026296149427:web:a31c986043c9597a3787c6',
    messagingSenderId: '1026296149427',
    projectId: 'mobile-3b99c',
    authDomain: 'mobile-3b99c.firebaseapp.com',
    storageBucket: 'mobile-3b99c.firebasestorage.app',
    measurementId: 'G-G3RCMXEJZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsCKiRl2yBqMXd6V6uzS6WlAo4uevXNtw',
    appId: '1:1026296149427:android:20b9b93e5d9869fd3787c6',
    messagingSenderId: '1026296149427',
    projectId: 'mobile-3b99c',
    storageBucket: 'mobile-3b99c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpD18vOWC4nfTPYNXU62p1cf9dIZAnzYA',
    appId: '1:1026296149427:ios:fbd7adca0c84a2383787c6',
    messagingSenderId: '1026296149427',
    projectId: 'mobile-3b99c',
    storageBucket: 'mobile-3b99c.firebasestorage.app',
    iosBundleId: 'com.example.th2SmartNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpD18vOWC4nfTPYNXU62p1cf9dIZAnzYA',
    appId: '1:1026296149427:ios:fbd7adca0c84a2383787c6',
    messagingSenderId: '1026296149427',
    projectId: 'mobile-3b99c',
    storageBucket: 'mobile-3b99c.firebasestorage.app',
    iosBundleId: 'com.example.th2SmartNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfOOhVnCloxCJZ5cqrl1-xBihbPVUK-sw',
    appId: '1:1026296149427:web:6b9968c59f40fabd3787c6',
    messagingSenderId: '1026296149427',
    projectId: 'mobile-3b99c',
    authDomain: 'mobile-3b99c.firebaseapp.com',
    storageBucket: 'mobile-3b99c.firebasestorage.app',
    measurementId: 'G-7WHVV299W0',
  );
}
